spring:
  application:
    name: SpringRedisCacheDemo
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: none
    show-sql: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  sql:
    init:
      schema-locations: classpath:create.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    port: 6379
    host: localhost
  cache:
    redis:
      time-to-live: 60000
    cache-names: articles